services:
  frontend:
    image: node:18-alpine
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - ./fe:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    image: golang:1.20-alpine
    container_name: golang_app
    working_dir: /go/src/app
    volumes:
      - ./be:/go/src/app
    ports:
      - "8080:8080"
    command: sh -c "go mod tidy && go run main.go"
    environment:
      - GO_ENV=development
